### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by kiruhasas22** [TrianglyRU/OrbinautFramework#10]
___________________________________________
############################################################################################
ERROR in
action number 1
of Draw Event
for object Player:

index out of bounds request 0 maximum size is 0############################################################################################
gml_Script_palette_set_colour (line 11)
gml_Script_palette_sync_colour (line 10)
gml_Script_PlayerSuperPalettesProcess (line 41)
gml_Object_Player_Draw_0 (line 9)

**Comment by kiruhasas22** [comment]
(and when orbian framework 2?)

**Comment by TrianglyRU** [comment]
We do not provide help with development here. OF1 does not have this problem out of the box, therefore it is an issue caused by whatever you've done
