### ISSUE TITLE
Hundreds of errors + Crash on entering the Test Level

### ISSUE THREAD

**Issue by kingthememer** [TrianglyRU/OrbinautFramework#11]
for some strange reason, after opening orbinaut im left with a shit ton of errors and i cant seem to make any real gameplay work

screenshot of errors:
![image](https://github.com/TrianglyRU/OrbinautFramework/assets/111393199/10598a5e-0fff-4bfc-8727-367fca96e069)

footage of crash:
https://github.com/TrianglyRU/OrbinautFramework/assets/111393199/0f5601f9-c849-4215-a513-02056a68d338

screenshot of crash message:
![image](https://github.com/TrianglyRU/OrbinautFramework/assets/111393199/db942e6d-375c-4f35-be82-9f9936566e2c)

ill admit im very new to gamemaker, but i cant seem to find any way around these issues
any help would be greatly appreciated

**Comment by kingthememer** [comment]
nevermind turns out it was a version issue

IMPORTANT:
if anyone has this issue too, use the STABLE version of gamemaker 2 NOT the monthly version

**Comment by TrianglyRU** [comment]
That's correct. Orbinaut is expected to be used with latest stable GameMaker version. I'd also recommend to turn off the Feather because the framework was not designed with it in mind

**Comment by Mariosonicman91** [comment]
I Downloaded the LTS version but with OrbinautFramework 1.4, it opens to read only mode, which I looked up and it means there's something LTS isn't compatible with in the code. What's the big deal? Which version do I use???
![Screenshot (143)](https://github.com/TrianglyRU/OrbinautFramework/assets/155042282/cf91614d-0bcb-4b3f-9481-430d575c50e3)
