### ISSUE TITLE
minor spelling mistake

### ISSUE THREAD

**Issue by SinexProgs** [TrianglyRU/OrbinautFramework#13]
[here](https://github.com/TrianglyRU/OrbinautFramework?tab=readme-ov-file#wiki)
"semi-complited". should be "semi-completed"
i win
![ur-mom-gottem](https://github.com/TrianglyRU/OrbinautFramework/assets/52968560/43aafc7f-ec08-49c8-b265-7e704ad825c1)

**Comment by TrianglyRU** [comment]
![изображение](https://github.com/TrianglyRU/OrbinautFramework/assets/45323263/556eff02-bf85-4ee3-8e52-d359536042e7)
