### ISSUE TITLE
Using LTS results in read only mode, using Monthly results in hundreds of errors, warnings, and suggestions.

### ISSUE THREAD

**Issue by Mariosonicman91** [TrianglyRU/OrbinautFramework#15]
I'm very new to Gamemaker, and was planning on it being the next step up from Scratch.mit.edu. I wanted to create a fangame, and I looked around, and saw Orbinaut Framework. Long story short, I downloaded the Windows Monthly from the official website, and it resulted in hundreds of errors, warnings, and suggestions. Then, I tried LTS, as I read (and even commented, before I realized it was closed) on this thread: https://github.com/TrianglyRU/OrbinautFramework/issues/11 - that Orbinaut Framework was meant for the latest stable release, yet it opened in read only mode, which meant that there were newer functions and whatnot the LTS version didn't recognize/couldn't execute (I have no clue what I'm talking about.) What am I missing?
![Screenshot (143)](https://github.com/TrianglyRU/OrbinautFramework/assets/155042282/d3f21c30-3627-41ec-8e99-d1c68fb26065)

**Comment by TrianglyRU** [comment]
You've got "errors" from Feather, which is a relatively new thing to GameMaker. Orbinaut was made before it was introduced, so it false-reports a lot. Disable it in the settings and you're good to go. I'll note that in the release page

Also, if you are new to GameMaker, I do not recommend Orbinaut as a starting point as we abandon a lot of GameMaker stuff there and use our own solutions. Spend a week or two with GameMaker's very own tutorials to get used to it first

**Comment by Mariosonicman91** [comment]
> You've got "errors" from Feather, which is a relatively new thing to GameMaker. Orbinaut was made before it was introduced, so it false-reports a lot. Disable it in the settings and you're good to go. I'll note that in the release page
> 
> Also, if you are new to GameMaker, I do not recommend Orbinaut as a starting point as we abandon a lot of GameMaker stuff there and use our own solutions. Spend a week or two with GameMaker's very own tutorials to get used to it first

Thank you! If I'm having too much trouble with GameMaker, I'll go find some general tutorials, but I'd like to take the risk.
