### ISSUE TITLE
Project just refuses to open without crashing on Mac

### ISSUE THREAD

**Issue by Paradexaad** [TrianglyRU/OrbinautFramework#19]
I don't know if this is a Mac only thing or if it's because my Mac isn't good enough but everytime I open the yyz file or project it won't work

**Comment by TrianglyRU** [comment]
Please provide more details, I literally can't do anything with what you said. Knowing your MacOS & GameMaker version would help

**Comment by TrianglyRU** [comment]
I'm closing the issue until further response
