### ISSUE TITLE
Wait what

### ISSUE THREAD

**Issue by SonicOrbinautFramework** [TrianglyRU/OrbinautFramework#7]
___________________________________________
############################################################################################
ERROR in
action number 1
of Create Event
for object TitleScreen:

Variable Palette.FadeValue(100086, -2147483648) not set before reading it.
 at gml_Script_fade_perform (line 11) -     if InstantFade or !(Palette.FadeValue mod 756)
############################################################################################
gml_Script_fade_perform (line 11)
gml_Object_TitleScreen_Create_0 (line 67) -               fade_perform(ModeFrom, BlendBlack, 1);

![image](https://user-images.githubusercontent.com/111817133/219905638-887f7387-c71c-495f-8fc5-cfd06ad7fa3d.png)
what happened?

I should be posting this in the Discord server, but the invite link has expired.
(BTW, version is 3.02)

**Comment by TrianglyRU** [comment]
First, issues tab exists for reporting an actual issues. Your issue is that Palette controller doesn't exist.
Second, this is GHZR. We do not provide any support on that
Third, https://github.com/TrianglyRU/OrbinautFramework/wiki/III.-Creating-a-New-Stage
