### ISSUE TITLE
Why is the counter sprites offset?

### ISSUE THREAD

**Issue by AaRonTheGameDev** [TrianglyRU/OrbinautFramework#8]
The counter sprites are not where it's supposed to be. I have uninstalled and reinstalled GameMaker and redownloaded the Orbinaut Framework and the counter sprites are still offset.

![image](https://github.com/TrianglyRU/OrbinautFramework/assets/83292322/41793f4d-7012-4ba9-90d2-14f80065b549)

Also, TSZ isn't set up by default like it used to be.

**Comment by TrianglyRU** [comment]
YoYo fixed the sprite fonts bug in the latest update. You need to move counters back manually by editing the code or changing the origin offset

Orbinaut 1 is not updated anymore, I am not responsible for any issues caused by the GameMaker updates

**Comment by AaRonTheGameDev** [comment]
Ok, Thanks for replaying.

**Comment by TrianglyRU** [comment]
Added the issue fix to the wiki
https://github.com/TrianglyRU/OrbinautFramework/wiki/V.-Extra:-Additional-Fixes-&-Improvements
