### ISSUE TITLE
How do i create new color palletes?

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [TrianglyRU/OrbinautFramework#9]
title, currently i have two sprites, one that's normal and one that's super form, currently the super form doesn't use sonic's blue color, hence why it doesn't change of colors, i wonder how do i make so i can use a different color palleted or create a new one.

**Comment by TrianglyRU** [comment]
Hi! Palettes are loaded from a palette lists stored in the Texture Data folder. What palette lists are loaded is determined by palette_load function called in PaletteSetup script

**Comment by FriskTheFallenHuman** [comment]
> Hi! Palettes are loaded from palette lists stored in the Texture Data folder. What palette lists are loaded is determined by palette_load function called in PaletteSetup script

Oh, thank you! has for the way on how the palleted should be create, the order of the pixels matters, or it can be something like loading an image in aseprite and saving the pallet has png and adding them into Game Maker right?

**Comment by TrianglyRU** [comment]
If you don't want to shift your colours, the order doesn't matter
